name: Enviar Feedback

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v2

    - name: Adicionar Feedback
      run: echo "Feedback: ${{ github.event_name }}" >> feedback.txt

    - name: Commit e Push das Alterações
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add feedback.txt
        git commit -m "Adicionando feedback"
        git push
